=encoding utf8

=head1 NAME

perlbook - Perl 书籍信息

=head1 DESCRIPTION

由 Larry Wall 等人编写的骆驼书 (官方名称为 I<Perl 语言编程, 第三版>)
是一本覆盖 Perl 各个方面的权威参考著作。
你可以从 O'Reilly & Associates (联系电话：1-800-998-9938) 订购该书及其他 Perl 书籍。
本地/海外联系电话为 +1 707 829 0515。
如果能找到一份 O'Reilly 订货单，你也可以向 +1 707 829 0104 发送传真。
如果你能上网，可以到 L<http://www.oreilly.com/> 在线填写订货单。


其他出自不同作者和出版商的 Perl 书籍可以在 L<perlfaq2> 中或
L<http://books.perl.org/> 的页面上找到列表。

=head1 TRANSLATORS

ChaosLawful